### ISSUE TITLE
Server-side API is broken

### ISSUE THREAD

**Issue by artpol84** [pmix/releases#8]
Hi,
Thanks to @dannyauble, minor API violation was detected at the server-side.
In the following commit:
https://github.com/pmix/releases/commit/7b4a371721fc6d2407b1f4ceb405acfc6e0ac481#diff-d48334f970184ceb6407aaa4bff6f11eL339

`struct pmix_info_t` was renamed to `struct pmix_info`.

This leads to the error in the SLURM plugin in the following line:
https://github.com/SchedMD/slurm/blob/master/src/plugins/mpi/pmix/pmixp_client.c#L392
with the following error:
```
cc1: warnings being treated as errors
pmixp_client.c: In function '_set_procdatas':
pmixp_client.c:392: error: assignment from incompatible pointer type
make: *** [pmixp_client.lo] Error 1
```

The problem here is that at line https://github.com/pmix/releases/blob/v1.1/include/pmix/pmix_common.h#L398 the field `array` has type `struct pmix_info`.
and only later (https://github.com/pmix/releases/blob/v1.1/include/pmix/pmix_common.h#L506:L509) the official type `pmix_info_t` is declared.

It's easy to fix this in the plugin, but we will lose backward compatibility with 1.1.3. Since it wasn't used in production anyway it might be a "no-problem",  However it's not a good approach in general.

**Comment by rhc54** [comment]
I'm afraid there was no way to avoid it - the prior declarations could not be compiled under C++

**Comment by artpol84** [comment]
Ok, so the SLURM plugin will be fixed to use `pmix_info_t` type (which sounds like a better approach compared to the current one) and won't be backward compatible with PMIx versions older than 1.1.4.

**Comment by rhc54** [comment]
Hmmm...I believe that C++ would accept us declaring "struct pmix_info_t" instead of pmix_info. Would that resolve the problem? We could test it and see.

**Comment by rhc54** [comment]
To be clear, the C++ problem was with the following:

```c
struct pmix_info_t;

typedef struct {
...
} pmix_info_t;
```

What it needed was to have the name of the forward-declaration in the typedef:

```c
struct pmix_info;

typedef struct pmix_info {
...
} pmix_info_t;
```

Not sure we had to rename the original struct declaration.

**Comment by artpol84** [comment]
I already tried that and C returned error.
I was surprised actually, I know that C and C++ handle typedef differently.
In any case using "struct pmix_info_t" in the user code is not correct from
my perspective. It can be only pmix_info_t.

пятница, 29 апреля 2016 г. пользователь rhc54 написал:

> Hmmm...I believe that C++ would accept us declaring "struct pmix_info_t"
> instead of pmix_info. Would that resolve the problem? We could test it and
> see.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/pmix/releases/issues/8#issuecomment-215616502>
>


-- 
-----
Best regards, Artem Polyakov
(Mobile mail)

**Comment by rhc54** [comment]
Rats - okay, no other option then. Thanks!

**Comment by artpol84** [comment]
Ok, I checked "struct pmix_info_t" variant again (I wasn't satisfied with compiler failure because I couldn't understand it).
And it was my bad - I changed the wrong pmix_common.h (in the sources instead of installation ;). So no surprises that it didn't improved anything because pmix_common.h in the installation dir remained the same.

So this approach:
```C
struct pmix_info_t;

typedef struct pmix_info_array {
    size_t size;
    struct pmix_info_t *array;
} pmix_info_array_t;

...
typedef struct pmix_info_t {
    char key[PMIX_MAX_KEYLEN+1];  // ensure room for the NULL terminator
    pmix_value_t value;
} pmix_info_t;
```
works fine and I think that we should change to this.

However regarding to a plugin I still think that using `struct pmix_info_t` is not correct. The official data type is `pmix_info_t` and it should be used everywhere outside of the pmix lib. So I vote to have the plugin changed to conform to this statement.

**Comment by rhc54** [comment]
Agreed, on both counts - thanks! Will you please make the change?

**Comment by artpol84** [comment]
Sure.

пятница, 29 апреля 2016 г. пользователь rhc54 написал:

> Agreed, on both counts - thanks! Will you please make the change?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/pmix/releases/issues/8#issuecomment-215738397>
>


-- 
-----
Best regards, Artem Polyakov
(Mobile mail)

**Comment by rhc54** [comment]
Repos have been consolidated into pmix/master
